language: python
python:
  - "3.5.1"

script:
  - python examples/validate.py
  - python find-latest-schemas.py schemas/ schemas-latest/
  - cd $TRAVIS_BUILD_DIR/schemas && tar -zcvf ../event-types-all.tar.gz *
  - cd $TRAVIS_BUILD_DIR/schemas-latest && tar -zcvf ../event-types-latest.tar.gz *
deploy:
  provider: releases
  api_key:
    secure: r7X89ZsZpFFbtY7R5an/UoCz+KooCQ0rXcOgx/t/xotdN4itT3yPekrnMsXKfEni9xaJ0HVFYZ+XpkuXcj2nKySGgi72VFSE+4qjFm2Zn99v5D/TH2JtTOmscrlRJbCDsboiPHk55YOICqNdH0M1sI8AaGyM6kTUsiBnvA5ZslhbA93JnTSnAuP6Sne495aXsCJSBzDgyCHEk4eNNOYv6+dK5e1iCiOi/sJuvYnKTo1hA+UXFlnI6NUYN+S6EJ4onmfCiFrMOT+kzc0lv0dCQSP094KBwCqwkSJyVK1b6dxKuuuc2Zc47xJaaiS0f3YBIyFPETLk7+t+OFYl33zWHwLaitDN/fAYYkL7ml63MPJ5+djfjPUSclclIkoI6SeyvDMLNOJAmU9/3cVKLy3kjOBCoCgYfD9vbvlo3WPcopJoTgfITn0K5ONZRdB5RkTESZBobdbcAr9NO7xBKAyUaAvDKHN3AGKVpfcf3akOFn6DV2BLm3ZTAICozpNOGaQlR4Y9dHC0e82sgoMXrP29M9JNhpqGSTcfcMD/TDDAMjnya8Y6CocYHi/qPxZqCezb+8uuqzDEf7Hnd/ycylbEGCQJFU9vtRogoJ8z54s1ZVT9cGZjCXEoy9LULldRyUthI1SwPrmXjnEX05yo2xs0sqcuRooaE2J64LzYuj+JCMQ=
  file:
    - event-types-all.tar.gz
    - event-types-latest.tar.gz
  skip_cleanup: true
  on:
    tags: true
